"""baseline schema

Revision ID: 33e7716425a6
Revises:
Create Date: 2026-05-18 20:49:20.830504

"""
from alembic import op
import sqlalchemy as sa



revision = '33e7716425a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_stock',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('turnoverratio', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('mktcap', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('wma10', sa.Float(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('exam_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='试题描述'),
    sa.Column('type', sa.Integer(), nullable=False, comment='试题类型, 0: 单选题, 1: 多选题, 2: 是非题'),
    sa.Column('score', sa.Integer(), nullable=False, comment='试题分数'),
    sa.Column('right_answer', sa.String(length=16), nullable=False, comment='正确答案'),
    sa.Column('option_a', sa.String(length=32), nullable=False, comment='选项A'),
    sa.Column('option_b', sa.String(length=32), nullable=False, comment='选项B'),
    sa.Column('option_c', sa.String(length=32), nullable=True, comment='选项C'),
    sa.Column('option_d', sa.String(length=32), nullable=True, comment='选项D'),
    sa.Column('option_e', sa.String(length=32), nullable=True, comment='选项E'),
    sa.Column('option_f', sa.String(length=32), nullable=True, comment='选项F'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_question_title'), 'exam_question', ['title'], unique=False)
    op.create_table('exam_result',
    sa.Column('user_nickname', sa.String(length=128), nullable=False, comment='试题描述'),
    sa.Column('score', sa.Integer(), nullable=False, comment='考试得分'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_nickname')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=True),
    sa.Column('totals', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('liquid_assets', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('reserved', sa.Float(), nullable=True),
    sa.Column('reserved_per_share', sa.Float(), nullable=True),
    sa.Column('esp', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('time_2_market', sa.String(length=16), nullable=True),
    sa.Column('undp', sa.Float(), nullable=True),
    sa.Column('perundp', sa.Float(), nullable=True),
    sa.Column('rev', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('gpr', sa.Float(), nullable=True),
    sa.Column('npr', sa.Float(), nullable=True),
    sa.Column('holders', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('investment_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False, comment='标题'),
    sa.Column('category', sa.String(length=32), nullable=True, comment='股票名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='排序优先级'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_knowledge_category'), 'investment_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_investment_knowledge_title'), 'investment_knowledge', ['title'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('eps_yoy', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('epcf', sa.Float(), nullable=True),
    sa.Column('net_profits', sa.Float(), nullable=True),
    sa.Column('profits_yoy', sa.Float(), nullable=True),
    sa.Column('report_date', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_selected_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('labels', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'code', name='uix_email_code')
    )
    op.create_index('ix_email_code', 'self_selected_stock', ['email', 'code'], unique=False)
    op.create_table('stock_cashflow_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('cf_sales', sa.Float(), nullable=True, comment='经营现金净流量对销售收入比率'),
    sa.Column('rateofreturn', sa.Float(), nullable=True, comment='资产的经营现金流量回报率'),
    sa.Column('cf_nm', sa.Float(), nullable=True, comment='经营现金净流量与净利润的比率'),
    sa.Column('cf_liabilities', sa.Float(), nullable=True, comment='经营现金净流量对负债比率'),
    sa.Column('cashflowratio', sa.Float(), nullable=True, comment='现金流量比率'),
    sa.Column('year', sa.Integer(), nullable=False, comment='财报年份'),
    sa.Column('season', sa.Integer(), nullable=False, comment='财报季度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_cashflow_report_code'), 'stock_cashflow_report', ['code'], unique=False)
    op.create_index(op.f('ix_stock_cashflow_report_name'), 'stock_cashflow_report', ['name'], unique=False)
    op.create_index(op.f('ix_stock_cashflow_report_season'), 'stock_cashflow_report', ['season'], unique=False)
    op.create_index(op.f('ix_stock_cashflow_report_year'), 'stock_cashflow_report', ['year'], unique=False)
    op.create_table('stock_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_cluster_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=16), nullable=False),
    sa.Column('parent_code', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('corr', sa.Float(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_debtpaying_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('currentratio', sa.Float(), nullable=True, comment='流动比率'),
    sa.Column('quickratio', sa.Float(), nullable=True, comment='速动比率'),
    sa.Column('cashratio', sa.Float(), nullable=True, comment='现金比率'),
    sa.Column('icratio', sa.Float(), nullable=True, comment='利息支付倍数'),
    sa.Column('sheqratio', sa.Float(), nullable=True, comment='股东权益比率'),
    sa.Column('adratio', sa.Float(), nullable=True, comment='股东权益增长率'),
    sa.Column('year', sa.Integer(), nullable=False, comment='财报年份'),
    sa.Column('season', sa.Integer(), nullable=False, comment='财报季度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_debtpaying_report_code'), 'stock_debtpaying_report', ['code'], unique=False)
    op.create_index(op.f('ix_stock_debtpaying_report_name'), 'stock_debtpaying_report', ['name'], unique=False)
    op.create_index(op.f('ix_stock_debtpaying_report_season'), 'stock_debtpaying_report', ['season'], unique=False)
    op.create_index(op.f('ix_stock_debtpaying_report_year'), 'stock_debtpaying_report', ['year'], unique=False)
    op.create_table('stock_growth_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('mbrg', sa.Float(), nullable=True, comment='主营业务收入增长率(%)'),
    sa.Column('nprg', sa.Float(), nullable=True, comment='净利润增长率(%)'),
    sa.Column('nav', sa.Float(), nullable=True, comment='净资产增长率'),
    sa.Column('targ', sa.Float(), nullable=True, comment='总资产增长率'),
    sa.Column('epsg', sa.Float(), nullable=True, comment='每股收益增长率'),
    sa.Column('seg', sa.Float(), nullable=True, comment='股东权益增长率'),
    sa.Column('year', sa.Integer(), nullable=False, comment='财报年份'),
    sa.Column('season', sa.Integer(), nullable=False, comment='财报季度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_growth_report_code'), 'stock_growth_report', ['code'], unique=False)
    op.create_index(op.f('ix_stock_growth_report_name'), 'stock_growth_report', ['name'], unique=False)
    op.create_index(op.f('ix_stock_growth_report_season'), 'stock_growth_report', ['season'], unique=False)
    op.create_index(op.f('ix_stock_growth_report_year'), 'stock_growth_report', ['year'], unique=False)
    op.create_table('stock_labels',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('labels', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('stock_operation_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('arturnover', sa.Float(), nullable=True, comment='应收账款周转率(次)'),
    sa.Column('arturndays', sa.Float(), nullable=True, comment='应收账款周转天数(天)'),
    sa.Column('inventory_turnover', sa.Integer(), nullable=True, comment='存货周转率(次)'),
    sa.Column('inventory_days', sa.Integer(), nullable=True, comment='存货周转天数(天)'),
    sa.Column('currentasset_turnover', sa.Integer(), nullable=True, comment='流动资产周转率(次)'),
    sa.Column('currentasset_days', sa.Integer(), nullable=True, comment='流动资产周转天数(天)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='财报年份'),
    sa.Column('season', sa.Integer(), nullable=False, comment='财报季度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_operation_report_code'), 'stock_operation_report', ['code'], unique=False)
    op.create_index(op.f('ix_stock_operation_report_name'), 'stock_operation_report', ['name'], unique=False)
    op.create_index(op.f('ix_stock_operation_report_season'), 'stock_operation_report', ['season'], unique=False)
    op.create_index(op.f('ix_stock_operation_report_year'), 'stock_operation_report', ['year'], unique=False)
    op.create_table('stock_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('accu_rate', sa.Float(), nullable=False, comment='精确度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prediction_code'), 'stock_prediction', ['code'], unique=False)
    op.create_index(op.f('ix_stock_prediction_name'), 'stock_prediction', ['name'], unique=False)
    op.create_table('stock_profit_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('roe', sa.Float(), nullable=True, comment='净资产收益率(%)'),
    sa.Column('net_profit_ratio', sa.Float(), nullable=True, comment='净利率(%)'),
    sa.Column('gross_profit_rate', sa.Float(), nullable=True, comment='毛利率(%)'),
    sa.Column('net_profits', sa.Float(), nullable=True, comment='净利润(万元)'),
    sa.Column('eps', sa.Float(), nullable=True, comment='每股收益'),
    sa.Column('business_income', sa.Float(), nullable=True, comment='营业收入(百万元)'),
    sa.Column('bips', sa.Float(), nullable=True, comment='每股主营业务收入(元)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='财报年份'),
    sa.Column('season', sa.Integer(), nullable=False, comment='财报季度'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_profit_report_code'), 'stock_profit_report', ['code'], unique=False)
    op.create_index(op.f('ix_stock_profit_report_name'), 'stock_profit_report', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('xueqiu_report_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_code', sa.String(length=8), nullable=False, comment='股票代码'),
    sa.Column('security_name', sa.String(length=8), nullable=False, comment='股票名称'),
    sa.Column('report_type', sa.Integer(), nullable=False, comment='报表类型 0: 资产负债表 1: 利润分配表 2: 现金流量表'),
    sa.Column('report_data', sa.Text(), nullable=False, comment='报表内容，json格式'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xueqiu_report_info_security_code'), 'xueqiu_report_info', ['security_code'], unique=False)
    op.create_index(op.f('ix_xueqiu_report_info_security_name'), 'xueqiu_report_info', ['security_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xueqiu_report_info_security_name'), table_name='xueqiu_report_info')
    op.drop_index(op.f('ix_xueqiu_report_info_security_code'), table_name='xueqiu_report_info')
    op.drop_table('xueqiu_report_info')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_profit_report_name'), table_name='stock_profit_report')
    op.drop_index(op.f('ix_stock_profit_report_code'), table_name='stock_profit_report')
    op.drop_table('stock_profit_report')
    op.drop_index(op.f('ix_stock_prediction_name'), table_name='stock_prediction')
    op.drop_index(op.f('ix_stock_prediction_code'), table_name='stock_prediction')
    op.drop_table('stock_prediction')
    op.drop_index(op.f('ix_stock_operation_report_year'), table_name='stock_operation_report')
    op.drop_index(op.f('ix_stock_operation_report_season'), table_name='stock_operation_report')
    op.drop_index(op.f('ix_stock_operation_report_name'), table_name='stock_operation_report')
    op.drop_index(op.f('ix_stock_operation_report_code'), table_name='stock_operation_report')
    op.drop_table('stock_operation_report')
    op.drop_table('stock_labels')
    op.drop_index(op.f('ix_stock_growth_report_year'), table_name='stock_growth_report')
    op.drop_index(op.f('ix_stock_growth_report_season'), table_name='stock_growth_report')
    op.drop_index(op.f('ix_stock_growth_report_name'), table_name='stock_growth_report')
    op.drop_index(op.f('ix_stock_growth_report_code'), table_name='stock_growth_report')
    op.drop_table('stock_growth_report')
    op.drop_index(op.f('ix_stock_debtpaying_report_year'), table_name='stock_debtpaying_report')
    op.drop_index(op.f('ix_stock_debtpaying_report_season'), table_name='stock_debtpaying_report')
    op.drop_index(op.f('ix_stock_debtpaying_report_name'), table_name='stock_debtpaying_report')
    op.drop_index(op.f('ix_stock_debtpaying_report_code'), table_name='stock_debtpaying_report')
    op.drop_table('stock_debtpaying_report')
    op.drop_table('stock_cluster_item')
    op.drop_table('stock_cluster')
    op.drop_index(op.f('ix_stock_cashflow_report_year'), table_name='stock_cashflow_report')
    op.drop_index(op.f('ix_stock_cashflow_report_season'), table_name='stock_cashflow_report')
    op.drop_index(op.f('ix_stock_cashflow_report_name'), table_name='stock_cashflow_report')
    op.drop_index(op.f('ix_stock_cashflow_report_code'), table_name='stock_cashflow_report')
    op.drop_table('stock_cashflow_report')
    op.drop_index('ix_email_code', table_name='self_selected_stock')
    op.drop_table('self_selected_stock')
    op.drop_table('report')
    op.drop_index(op.f('ix_investment_knowledge_title'), table_name='investment_knowledge')
    op.drop_index(op.f('ix_investment_knowledge_category'), table_name='investment_knowledge')
    op.drop_table('investment_knowledge')
    op.drop_table('instrument')
    op.drop_table('exam_result')
    op.drop_index(op.f('ix_exam_question_title'), table_name='exam_question')
    op.drop_table('exam_question')
    op.drop_table('business_stock')
    # ### end Alembic commands ###
